<?php 
    if(!isset($bien_bao_mat)){exit();}
?>
<?php
    if(isset($_POST['bieu_mau_them_menu_ngang']))
    {
        include("chucnang/menungang/themmenungangvaocsdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_sua_menu_ngang']))
    {
        include("chucnang/menungang/suamenungangotrongcsdl.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_menu_ngang']))
    {
        include("chucnang/menungang/xoamenungang.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_them_menu_doc']))
    {
        include("chucnang/menudoc/themmenudocvaocsdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_sua_menu_doc']))
    {
        include("chucnang/menudoc/suamenudocotrongcsdl.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_menu_doc']))
    {
        include("chucnang/menudoc/xoamenudoc.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_them_san_pham']))
    {
        include("chucnang/sanpham/themsanphamvaocsdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_sua_san_pham']))
    {
        include("chucnang/sanpham/suasanphamotrongcsdl.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_san_pham']))
    {
        include("chucnang/sanpham/xoasanpham.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_hoa_don']))
    {
        include("chucnang/hoadon/xoahoadon.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_hoa_don_o_trang_chi_tiet']))
    {
        include("chucnang/hoadon/xoahoadonotrangchitiet.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_san_pham_trang_chu']))
    {
        include("chucnang/sanphamtrangchu/suasanphamtrangchu.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_san_pham_noi_bat']))
    {
        include("chucnang/sanphamnoibat/suasanphamnoibat.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieumauthemslideshow']))
    {
        include("chucnang/slideshow/themslideshowvaocsdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_sua_slideshow']))
    {
        include("chucnang/slideshow/suaslideshowotrongcsdl.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_slideshow']))
    {
        include("chucnang/slideshow/xoaslideshow.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_sua_banner']))
    {
        include("chucnang/banner/suabannerotrongcsdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieumausuafooter']))
    {
        include("chucnang/footer/suafooterotrongcsdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_them_quang_cao_trai']))
    {
        include("chucnang/quangcaotrai/themquangcaotraivaocsdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieu_mau_sua_quang_cao_trai']))
    {
        include("chucnang/quangcaotrai/suaquangcaotraiotrongcsdl.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoa_quang_cao_trai']))
    {
        include("chucnang/quangcaotrai/xoaquangcaotrai.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieumauthemquangcaophai']))
    {
        include("chucnang/quangcaophai/themquangcaophaivaocsdl.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieumausuaquangcaophai']))
    {
        include("chucnang/quangcaophai/suaquangcaophaiotrongcsdl.php");
        trang_truoc_html();
    }
    if(isset($_GET['xoaquangcaophai']))
    {
        include("chucnang/quangcaophai/xoaquangcaophai.php");
        trang_truoc_html();
    }
    if(isset($_POST['bieumausuathongtinquantri']))
    {
        include("chucnang/quantri2/suathongtinquantriotrongcsdl.php");
        trang_truoc_html();
    }    
    if(isset($_GET['thamso']))
    {
        if($_GET['thamso']=="thoat")
        {
            include("chucnang/quantri2/thoat.php");
            trang_truoc_html();
        }
    }
?>